# Use Brewdler gem to install (brewdle install)

brew 'zsh-completions'
brew 'zsh-syntax-highlighting'
brew 'coreutils'
brew 'git'
brew 'python'
brew 'mercurial'
brew 'zsh'
brew 'ruby-install'
brew 'ack'
brew 'colordiff'
brew 'jsonpp'
brew 'node'
brew 'wrk'
brew 'tree'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'htop'
brew 'tig'
brew 'httrack'
brew 'ansible'
brew 'ranger'
brew 'pgcli', args: ['build-from-source'] # use postgres.app instead of installing postgres from homebrew

brew 'caskroom/cask/brew-cask'

cask 'vmware-fusion'
cask 'vagrant'
cask 'macvim'
cask 'osxfuse'
