brew 'z'
brew 'pv'
brew 'jq'
brew 'zsh-completions'
brew 'git'
brew 'vim', args: ['head']
brew 'colordiff'
brew 'jsonpp'
brew 'tmux'
brew 'git-delta'
brew 'rbenv'
brew 'ripgrep'
brew 'fzf'
brew 'docker-completion'
brew 'nnn'
brew 'gcc'
brew 'duf'
brew 'rclone'
brew 'mosh'
brew 'gnupg'
brew 'git-remote-gcrypt'

if OS.mac?
  brew 'git-annex'
  brew 'zsh'
  brew 'rsync'
  brew 'tree'
  brew 'coreutils'
  brew 'reattach-to-user-namespace'
  brew 'trash'
  brew 'dnsmasq'
  brew 'htop'
  brew 'exiftool'
  brew 'mediainfo'
  brew 'yt-dlp'
  brew 'ffmpeg'
  brew 'mkvtoolnix'

  tap 'mutagen-io/mutagen'
  brew 'mutagen-io/mutagen/mutagen'

  cask 'kitty'
  cask 'ngrok'
end
