#!/usr/bin/env ruby

require 'fileutils'

source = File.expand_path(File.dirname(__FILE__) + '/..')
destination = File.expand_path('~')
host = `hostname -s`.strip

FileUtils.mkdir_p("#{destination}/.config/kitty")

def symlink(s, d)
  if File.exist?(d)
    puts "#{d} exists"
    puts "#{d} #{File.symlink?(d) ? 'is' : 'is not' } a symlink"
  else
    puts "creating symlink #{d} -> #{s}"
    File.symlink(s, d)
  end
  puts '--'
end

kitty_machine_conf = "#{source}/kitty-#{host}.conf"
if File.exist?(kitty_machine_conf)
  symlink("#{source}/kitty.conf", "#{destination}/.config/kitty/kitty.conf")
  symlink(kitty_machine_conf, "#{destination}/.config/kitty/this-machine.conf")
end

symlink("#{source}/gemrc", "#{destination}/.gemrc")
symlink("#{source}/gitconfig", "#{destination}/.gitconfig")
symlink("#{source}/gitignore_global", "#{destination}/.gitignore_global")
symlink("#{source}/tmux.conf", "#{destination}/.tmux.conf")
symlink("#{source}/vimrc", "#{destination}/.vimrc")
symlink("#{source}/zshrc", "#{destination}/.zshrc")
symlink("#{source}/zprofile", "#{destination}/.zprofile")
symlink("#{source}/zsh", "#{destination}/.zsh")
symlink("#{source}/pryrc", "#{destination}/.pryrc")
symlink("#{source}/irbrc", "#{destination}/.irbrc")
symlink("#{source}/colordiffrc", "#{destination}/.colordiffrc")
symlink("#{source}/psqlrc", "#{destination}/.psqlrc")
symlink("#{source}/bin", "#{destination}/.bin")
