#!/usr/bin/env ruby

require 'fileutils'

source = File.expand_path(File.dirname(__FILE__) + '/..')
destination = File.expand_path('~')

FileUtils.mkdir_p("#{destination}/.config/kitty")

File.symlink("#{source}/kitty.conf", "#{destination}/.config/kitty/kitty.conf")
File.symlink("#{source}/gemrc", "#{destination}/.gemrc")
File.symlink("#{source}/gitconfig", "#{destination}/.gitconfig")
File.symlink("#{source}/gitignore_global", "#{destination}/.gitignore_global")
File.symlink("#{source}/tmux.conf", "#{destination}/.tmux.conf")
File.symlink("#{source}/vimrc", "#{destination}/.vimrc")
File.symlink("#{source}/zshrc", "#{destination}/.zshrc")
File.symlink("#{source}/zprofile", "#{destination}/.zprofile")
File.symlink("#{source}/zsh", "#{destination}/.zsh")
File.symlink("#{source}/pryrc", "#{destination}/.pryrc")
File.symlink("#{source}/colordiffrc", "#{destination}/.colordiffrc")
File.symlink("#{source}/psqlrc", "#{destination}/.psqlrc")

File.symlink("#{source}/bin", "#{destination}/.bin")
