#!/usr/bin/env ruby

root_path = "~/"
plugins = [
  "https://github.com/mileszs/ack.vim",
  "https://github.com/raimondi/delimitmate",
  "https://github.com/altercation/vim-colors-solarized",
  "https://github.com/tpope/vim-commentary",
  "https://github.com/tpope/vim-endwise",
  "https://github.com/tpope/vim-eunuch",
  "https://github.com/tpope/vim-fugitive",
  "https://github.com/airblade/vim-gitgutter",
  "https://github.com/nathanaelkane/vim-indent-guides",
  "https://github.com/sheerun/vim-polyglot",
  "https://github.com/tpope/vim-rails",
  "https://github.com/tpope/vim-repeat",
  "https://github.com/mhinz/vim-sayonara",
  "https://github.com/justinmk/vim-sneak"
  "https://github.com/tpope/vim-surround",
  "https://github.com/tpope/vim-unimpaired",
  "https://github.com/tpope/vim-vinegar"
]

def install_plugins(root_path, plugins)
  Dir.chdir(File.expand_path("#{root_path}.vim/bundle/"))
  plugins.each do |repo|
    print "\n"
    system "git clone #{repo}"
  end
end

def extra_steps(root_path)
end

def do_install(root_path, plugins)
  Dir.chdir(File.expand_path(root_path))

  puts "\n\ncreating directory structure\n\n"
  system "mkdir -p #{root_path}.vim/_backup"
  system "mkdir -p #{root_path}.vim/_temp"
  system "mkdir -p #{root_path}.vim/_cache"
  system "mkdir -p #{root_path}.vim/autoload"
  system "mkdir -p #{root_path}.vim/bundle"

  puts "\n\ninstalling pathogen\n\n"
  system "curl -LSso #{root_path}/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim"

  puts "\n\ninstalling plugins\n\n"
  install_plugins(root_path, plugins)

  puts "\n\nrunning extra steps\n\n"
  extra_steps(root_path)
end

do_install(root_path, plugins) unless Dir.exists?(File.expand_path("#{root_path}.vim"))
